package com.sharkdom.constants.stripe;

import lombok.Getter;

import java.util.Locale;

@Getter
public enum StripePlanType {
    STANDARD_MONTHLY_INR("STANDARD_MONTHLY_INR"),
    PREMIUM_MONTHLY_INR("PREMIUM_MONTHLY_INR"),
    ENTERPRISE_MONTHLY_INR("ENTERPRISE_MONTHLY_INR"),
    STANDARD_YEARLY_INR("STANDARD_YEARLY_INR"),
    PREMIUM_YEARLY_INR("PREMIUM_YEARLY_INR"),
    ENTERPRISE_YEARLY_INR("ENTERPRISE_YEARLY_INR"),

    STANDARD_MONTHLY_US("STANDARD_MONTHLY_US"),
    PREMIUM_MONTHLY_US("PREMIUM_MONTHLY_US"),
    ENTERPRISE_MONTHLY_US("ENTERPRISE_MONTHLY_US"),
    STANDARD_YEARLY_US("STANDARD_YEARLY_US"),
    PREMIUM_YEARLY_US("PREMIUM_YEARLY_US"),
    ENTERPRISE_YEARLY_US("ENTERPRISE_YEARLY_US"),

    STANDARD_MONTHLY_ONE("STANDARD_MONTHLY_ONE"),
    STANDARD_MONTHLY_TWO("STANDARD_MONTHLY_TWO"),
    STANDARD_MONTHLY_THREE("STANDARD_MONTHLY_THREE"),
    STANDARD_MONTHLY_FOUR("STANDARD_MONTHLY_FOUR"),
    STANDARD_YEARLY_ONE("STANDARD_YEARLY_ONE"),
    STANDARD_YEARLY_TWO("STANDARD_YEARLY_TWO"),
    STANDARD_YEARLY_THREE("STANDARD_YEARLY_THREE"),
    STANDARD_YEARLY_FOUR("STANDARD_YEARLY_FOUR"),

    PREMIUM_MONTHLY_ONE("PREMIUM_MONTHLY_ONE"),
    PREMIUM_MONTHLY_TWO("PREMIUM_MONTHLY_TWO"),
    PREMIUM_MONTHLY_THREE("PREMIUM_MONTHLY_THREE"),
    PREMIUM_MONTHLY_FOUR("PREMIUM_MONTHLY_FOUR"),
    PREMIUM_YEARLY_ONE("PREMIUM_YEARLY_ONE"),
    PREMIUM_YEARLY_TWO("PREMIUM_YEARLY_TWO"),
    PREMIUM_YEARLY_THREE("PREMIUM_YEARLY_THREE"),
    PREMIUM_YEARLY_FOUR("PREMIUM_YEARLY_FOUR"),

    ENTERPRISE_MONTHLY_ONE("ENTERPRISE_MONTHLY_ONE"),
    ENTERPRISE_MONTHLY_TWO("ENTERPRISE_MONTHLY_TWO"),
    ENTERPRISE_MONTHLY_THREE("ENTERPRISE_MONTHLY_THREE"),
    ENTERPRISE_MONTHLY_FOUR("ENTERPRISE_MONTHLY_FOUR"),
    ENTERPRISE_YEARLY_ONE("ENTERPRISE_YEARLY_ONE"),
    ENTERPRISE_YEARLY_TWO("ENTERPRISE_YEARLY_TWO"),
    ENTERPRISE_YEARLY_THREE("ENTERPRISE_YEARLY_THREE"),
    ENTERPRISE_YEARLY_FOUR("ENTERPRISE_YEARLY_FOUR"),

    STANDARD_MONTHLY_ONE_US("STANDARD_MONTHLY_ONE_US"),
    STANDARD_MONTHLY_TWO_US("STANDARD_MONTHLY_TWO_US"),
    STANDARD_MONTHLY_THREE_US("STANDARD_MONTHLY_THREE_US"),
    STANDARD_MONTHLY_FOUR_US("STANDARD_MONTHLY_FOUR_US"),
    STANDARD_YEARLY_ONE_US("STANDARD_YEARLY_ONE_US"),
    STANDARD_YEARLY_TWO_US("STANDARD_YEARLY_TWO_US"),
    STANDARD_YEARLY_THREE_US("STANDARD_YEARLY_THREE_US"),
    STANDARD_YEARLY_FOUR_US("STANDARD_YEARLY_FOUR_US"),

    PREMIUM_MONTHLY_ONE_US("PREMIUM_MONTHLY_ONE_US"),
    PREMIUM_MONTHLY_TWO_US("PREMIUM_MONTHLY_TWO_US"),
    PREMIUM_MONTHLY_THREE_US("PREMIUM_MONTHLY_THREE_US"),
    PREMIUM_MONTHLY_FOUR_US("PREMIUM_MONTHLY_FOUR_US"),
    PREMIUM_YEARLY_ONE_US("PREMIUM_YEARLY_ONE_US"),
    PREMIUM_YEARLY_TWO_US("PREMIUM_YEARLY_TWO_US"),
    PREMIUM_YEARLY_THREE_US("PREMIUM_YEARLY_THREE_US"),
    PREMIUM_YEARLY_FOUR_US("PREMIUM_YEARLY_FOUR_US"),

    ENTERPRISE_MONTHLY_ONE_US("ENTERPRISE_MONTHLY_ONE_US"),
    ENTERPRISE_MONTHLY_TWO_US("ENTERPRISE_MONTHLY_TWO_US"),
    ENTERPRISE_MONTHLY_THREE_US("ENTERPRISE_MONTHLY_THREE_US"),
    ENTERPRISE_MONTHLY_FOUR_US("ENTERPRISE_MONTHLY_FOUR_US"),
    ENTERPRISE_YEARLY_ONE_US("ENTERPRISE_YEARLY_ONE_US"),
    ENTERPRISE_YEARLY_TWO_US("ENTERPRISE_YEARLY_TWO_US"),
    ENTERPRISE_YEARLY_THREE_US("ENTERPRISE_YEARLY_THREE_US"),
    ENTERPRISE_YEARLY_FOUR_US("ENTERPRISE_YEARLY_FOUR_US");

    private final String planName;

    StripePlanType(String planName) {

        this.planName = planName
                .replace("_", " ")
                .toLowerCase(Locale.ROOT)
                .replace(" us", "")
                .replace(" inr", "")
                .replace(" one", "")
                .replace(" two", "")
                .replace(" three", "")
                .replace(" four", "");
    }
}
