package com.sharkdom.subscription.entity;

public enum ModuleName {

    // Monthly
    PARTNER_ONBOARDING_MONTHLY,
    PARTNER_MANAGEMENT_MONTHLY,
    DEAL_REGISTRATION_MONTHLY,
    PARTNER_MAPPING_MONTHLY,
    JOINT_GTM_BOARD_MONTHLY,
    PARTNER_ENABLEMNT_MONTHLY,

    // Quarterly
    PARTNER_ONBOARDING_QUARTERLY,
    PARTNER_MANAGEMENT_QUARTERLY,
    DEAL_REGISTRATION_QUARTERLY,
    PARTNER_MAPPING_QUARTERLY,
    JOINT_GTM_BOARD_QUARTERLY,
    PARTNER_ENABLEMNT_QUARTERLY,

    // Half Yearly
    PARTNER_ONBOARDING_HALFYEARLY,
    PARTNER_MANAGEMENT_HALFYEARLY,
    DEAL_REGISTRATION_HALFYEARLY,
    PARTNER_MAPPING_HALFYEARLY,
    JOINT_GTM_BOARD_HALFYEARLY,
    PARTNER_ENABLEMNT_HALFYEARLY,

    // Yearly
    PARTNER_ONBOARDING_YEARLY,
    PARTNER_MANAGEMENT_YEARLY,
    DEAL_REGISTRATION_YEARLY,
    PARTNER_MAPPING_YEARLY,
    JOINT_GTM_BOARD_YEARLY,
    PARTNER_ENABLEMNT_YEARLY
}