package com.sharkdom.quickstart.dto;

public enum RewardType {
    COMPANY_PROFILE_COMPLETION,
    FIRST_PARTNER_ADDED,
    DATA_SOURCE_CONNECTED,
    PARTNER_OPPORTUNITY_FOUND,
    FIRST_DEAL_REGISTERED,
    TEAMMATE_INVITED,
    ECOSYSTEM_GOAL_ACHIEVED
}